# Generated by Django 4.2 on 2025-04-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='countInStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
