products = [
    {
        "id": 1,
        "name": "Laptop",
        "price": 1200.00,
        "category": "Electronics",
        "stock": 10,
    },
    {
        "id": 2,
        "name": "Smartphone",
        "price": 799.49,
        "category": "Electronics",
        "stock": 25,
    },
    {
        "id": 3,
        "name": "Desk Chair",
        "price": 150.00,
        "category": "Furniture",
        "stock": 5,
    },
    {
        "id": 4,
        "name": "Coffee Maker",
        "price": 89.99,
        "category": "Appliances",
        "stock": 15,
    },
    {
        "id": 5,
        "name": "Headphones",
        "price": 199.99,
        "category": "Electronics",
        "stock": 30,
    },
    {
        "id": 6,
        "name": "Keyboard",
        "price": 49.99,
        "category": "Electronics",
        "stock": 50,
    },
    {
        "id": 7,
        "name": "Monitor",
        "price": 299.99,
        "category": "Electronics",
        "stock": 20,
    },
    {
        "id": 8,
        "name": "Blender",
        "price": 59.99,
        "category": "Appliances",
        "stock": 10,
    },
    {
        "id": 9,
        "name": "Television",
        "price": 2000.00,
        "category": "Electronics",
        "stock": 8,
    },
    {
        "id": 10,
        "name": "Gaming Mouse",
        "price": 69.99,
        "category": "Electronics",
        "stock": 40,
    },
]